language: csharp
sudo: required
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
mono: none
branches:
  only:
    - master
install:
  - ./build_travis-ci/get-dotnet.sh
script:
  - ./build_travis-ci/build.sh