language: csharp
sudo: true
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
mono: none
branches:
  only:
    - master
before_install:
  - chmod a+x ./00.build@travis-ci/get-dotnet.sh
  - chmod a+x ./00.build@travis-ci/build.sh
install:
  - ./00.build@travis-ci/get-dotnet.sh
script:
  - ./00.build@travis-ci/build.sh