lslsversion: '3.4'

services:
  serverconsoleapp.core:
    image: ${DOCKER_REGISTRY}serverconsoleappcore
    build:
      context: .
      dockerfile: Samples/SocketAsyncArgs.TCP.Echo.Server/ServerConsoleApp/ServerConsoleApp.Core/Dockerfile

  webapplication.aspnetcore.storeprocedureexecutor:
    image: ${DOCKER_REGISTRY}webapplicationaspnetcorestoreprocedureexecutor
    build:
      context: .
      dockerfile: Samples/WebApplication.ASPNETCore.StoreProcedureExecutor/Dockerfile

