FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.WebApplication.csproj", "Samples/MsSqlCodeDiffVersioning/"]
COPY ["StoreProcedureWebApiExecutor/StoreProcedureWebApiExecutor.Core/Microshaoft.StoreProcedureExecutorWebApiService.Core.csproj", "StoreProcedureWebApiExecutor/StoreProcedureWebApiExecutor.Core/"]
RUN dotnet restore "Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.WebApplication.csproj"
COPY . .
WORKDIR "/src/Samples/MsSqlCodeDiffVersioning"
RUN dotnet build "MsSqlCodeDiffVersioning.WebApplication.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MsSqlCodeDiffVersioning.WebApplication.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MsSqlCodeDiffVersioning.WebApplication.dll"]